#!/bin/bash

cd ./frontend/
npm run build
cd out
zip -r ../../upload.zip .
cd ../../

source ./.env
scp upload.zip $REMOTE_USER@$REMOTE_HOST:~/public_html/blog/upload.zip
ssh $REMOTE_USER@$REMOTE_HOST "cd ~/public_html/blog/ && unzip -o upload.zip && rm upload.zip"

